#!/bin/bash
set -e

if [ -z "$CI" ]; then
  export AZ_VERSION='local'
else
  export AZ_VERSION=${CI_BRANCH}.${CI_BUILD_NUMBER}.${CI_COMMIT}
fi

echo "################### Building parent-application ###################"
time jspm bundle src/main.js dist/build.js
echo "################### Parent Application built ###################"

echo "################### printing version to dist/az-version.js ###################"
# export AZ_BUILD_OBJECT=$(npm run -s getAzBuildObject)
echo "Printing version: ${AZ_VERSION}"
# echo "window.azBuild = $AZ_BUILD_OBJECT" > dist/alz-version.js
echo "window.azBuild = $AZ_VERSION" > dist/alz-version.js
echo "################### Version Printed ###################"
